USE codeup_test_db;
INSERT INTO albums (artist, name, release_date, sales, genre)
VALUES ('Michael Jackson', 'Thriller', 1982, 47.3, 'pop, post-disco, funk, rock'),
       ('AC/DC', 'Back in Black', 1980, 29.4, 'hard rock'),
       ('Meat Loaf', 'Bat Out of Hell', 1977, 21.7, 'hard rock, glam rock, heavy metal'),
       ('Pink Floyd', 'The Dark Side of the Moon', 1973, 29.4, 'Progressive rock'),
       ('Whitney Houston', 'The Bodyguard', 1992, 29.4, 'R&B, soul, pop, soundtrack'),
       ('Eagles', 'Their Greatest Hits (1971–1975)', 1976, 29.4, 'Country rock, soft rock, folk rock'),
       ('Bee Gees', 'Saturday Night Fever', 1977, 29.4, 'Disco'),
       ('Fleetwood Mac', 'Rumours', 1977, 29.4, 'Soft rock'),
       ('Shania Twain', 'Come On Over', 1997, 29.4, 'Country, pop'),
       ('Various Artists', 'Grease: The Original Soundtrack from the Motion Picture', 1978, 29.4, 'Rock and roll'),
       ('Led Zeppelin', 'Led Zeppelin IV', 1971, 29.4, 'Hard rock, heavy metal, folk rock'),
       ('Michael Jackson', 'Bad', 1987, 29.4, 'Pop, rhythm and blues, funk and rock'),
       ('Alanis Morissette', 'Jagged Little Pill', 1995, 29.4, 'Alternative rock'),
       ('Michael Jackson', 'Dangerous', 1991, 29.4, 'New jack swing, R&B and pop'),
       ('Celine Dion', 'Falling into You', 1996, 29.4, 'Pop, soft rock'),
       ('Eagles', 'Hotel California', 1976, 29.4, 'Soft rock'),
       ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 1967, 29.4, 'Rock'),
       ('Various Artists', 'Dirty Dancing', 1987, 29.4, 'Pop, rock, R&B'),
       ('Adele', '21', 2011, 29.4, 'Pop, soul'),
       ('Celine Dion', 'Let''s Talk About Love', 1997, 29.4, 'Pop, soft rock'),
       ('The Beatles', '1', 2000, 29.4, 'hard rock'),
       ('ABBA', 'Gold: Greatest Hits', 1992, 29.4, 'hard rock'),
       ('The Beatles', 'Abbey Road', 1969, 29.4, 'hard rock'),
       ('Bruce Springsteen', 'Born in the U.S.A.', 1984, 29.4, 'hard rock'),
       ('Dire Straits', 'Brothers in Arms', 1985, 29.4, 'hard rock'),
       ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 29.4, 'hard rock'),
       ('Metallica', 'Metallica', 1991, 29.4, 'hard rock'),
       ('Nirvana', 'Nevermind', 1991, 29.4, 'hard rock'),
       ('Pink FLoyd', 'The Wall', 1979, 29.4, 'hard rock'),
       ('Santana', 'Supernatural', 1999, 29.4, 'hard rock'),
       ('Madonna', 'The Immaculate Collection', 1990, 29.4, 'hard rock'),
       ('Guns N'' Roses', 'Appetite for Destruction', 1987, 29.4, 'hard rock');